package com.ackdev.statics;

public enum EnumStatus {
    SCHEDULED, INPROGRESS, ONHOLD, COMPLETE, CLOSED, UNSCHEDULED, NEW, PENDING, UNASSIGNED, SNOOZE, WAITING_ON_CLIENT, AWAITING_INSPECTION, CANCELLED, COMPLETE_AND_RESCHEDULE_ANNUALLY, INVOICED
}
